### ISSUE TITLE
Icons with a blurry look

### ISSUE THREAD

**Issue by msp-platforme** [ripe-tech/ripe-components-vue#471] opened 2021-03-26 10:41 UTC
## Description

Some icons we use across projects have a blurry look - it's due to anti-aliasing, when resizing the icon becomes blurry.
There is no one-size-fits-all solution in code, since different icons require different sizes to stop being blurry.

## Expected vs. Observed

| - | - |
| --- | --- |
| **Expected** | The icons look crisp. |
| **Observed** | The icons look blurred. |

## Screens

Two examples:
![icon](https://user-images.githubusercontent.com/72499843/112619422-3a68a900-8e1f-11eb-8c0a-136d13f96f47.png)
![icon 2](https://user-images.githubusercontent.com/72499843/112619433-3d639980-8e1f-11eb-86e0-4f6fcc744fcc.png)

**Comment by gcandal** [comment] 2021-03-26 11:01
@BeeMargarida please share the details of the investigation you did while trying to fix this.

**Comment by BeeMargarida** [comment] 2021-03-26 11:18
Based on these links ([here](https://stackoverflow.com/questions/57628106/why-is-my-resized-svg-icon-blurry-when-rendered) and [here](https://graphicdesign.stackexchange.com/questions/32100/quality-loss-when-scaling-down-svgs?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa)), the problem is due to the way the browser (and possibly system) deals with anti-aliasing.

When scaling down the SVGs, there are some sizes that cause the icon to become blurry. With the `add` icon specifically, we noticed that the size 17 fixes the blurry aspect, but size 18 becomes blurry. Since we are getting our icons from Ikonate, we experimented scaling down in their website. They only support export of sizes multiple of 8 (which does not match the sizes we use in the buttons), and when forcing the icons in Ikonate to match some of ours, the problem appeared as well (this using the same stroke-width of 1.5 and color). We export their icons in 48x48.
<hr>

Icon 48x48 with size 18 in ikonate<br>
![image](https://user-images.githubusercontent.com/25725586/112623924-d9dc6a80-8e24-11eb-8ac1-4eb54bb5167e.png)<br>
Icon 48x48 with size 17 in ikonate<br>
![image](https://user-images.githubusercontent.com/25725586/112623304-19568700-8e24-11eb-8f2b-1f2c2bed3781.png)<br>

<hr>

Icon 16x16 with size 18 in ikonate<br>
![image](https://user-images.githubusercontent.com/25725586/112623500-56bb1480-8e24-11eb-8506-e1a8be5d031f.png)<br>
Icon 16x16 with size 18 in ikonate<br>
![image](https://user-images.githubusercontent.com/25725586/112623561-65a1c700-8e24-11eb-8555-7d6cebfc9b77.png)<br>

<hr>

With this we can kind of assume that the original size has not much to do with the blurriness of the resizing. I also don't know if the icons themselves have some problem.

**Comment by joamag** [comment] 2021-03-26 17:24
Closing this as I believe we'll have to live with this limitation :(

**Closed by joamag** 2021-03-26 17:24 UTC
Labels: bug, triage
