### ISSUE TITLE
Implement support for regex input validation

### ISSUE THREAD

**Issue by Benedito0** [ripe-tech/ripe-components-vue#392] opened 2020-10-09 09:44 UTC
## Rationale

Our _input-ripe_ component as I am writing this, have no form of validation, input validation is a _must-have_
## Description

Use Regular Expression for value validation.

## Estimation

| Discipline | Estimation |
| --- | --- |
| **Software Development** | 0.1 days |

**Comment by gcandal** [comment] 2020-10-09 09:58
@Benedito0 please include some use-cases where this would prove useful.

**Comment by joamag** [comment] 2020-10-09 10:38
Closing this as a duplicate of a much larger project to bring validation to the client side

**Closed by joamag** 2020-10-09 10:38 UTC
Labels: feature-request 💡

**Comment by gcandal** [comment] 2020-10-09 11:12
@joamag it seems that Mauro's intent was to have a [uxf-like](https://github.com/hivesolutions/uxf/blob/master/js/ui/text_field.part.js#L94) functionality not for showing errors / red boxes / whatever but to prevent certain characters from being written. Would that be part of the form validation thread as well?
